config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "books" => "books#index"
  post "books" => "books#create"
  get "books/:id" => "books#show", as: 'book'
  get "books/:id/edit" => "books#edit", as: "edit_book"
  patch "books/:id" => "books#update" , as: "update_book"
  delete "books/:id" => "books#destroy", as: "destroy_book"

  root to: 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/booker.rb
class Booker < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
      flash[:success]="Book was successfully created."
    else
      @books = Book.all
      render :index
    end
  end

  def destroy
    booker = Book.find(params[:id])
    booker.destroy
    flash[:success] = "Book was successfully destroyed."
    redirect_to "/books"
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div class="alert">
    <div class="alert_message">
      <%if @book.errors.count == 1 %>
      1 error prohibited this book from being saved:
      <% else %>
      2 errors prohibited this book from being saved:
      <% end %>
    </div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
    <div>Title</div>
    <%= f.text_field :title, value: @book.title %>
    <div class="index_form">Body</div>
    <%= f.text_area :body, value: @book.body %>
    <div class="index_form edit_form"><%= f.submit 'Update Book' %></div>
  <% end %>
<% else %>
  <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
    <div>Title</div>
    <%= f.text_field :title, value: @book.title %>
    <div class="index_form">Body</div>
    <%= f.text_area :body, value: @book.body %>
    <div class="index_form edit_form"><%= f.submit 'Update Book' %></div>
  <% end %>
<% end %>
<%= link_to "Show", book_path(params[:id]), class: "edit_btn" %> | <%= link_to "Back","/books", class: "edit_btn" %>

app/views/books/index.html.erb
 <% flash.each do |message_type, message| %>
      <p class ="message_color"><%= message %></p>
 <% end %>
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tbody>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<h2>New book</h2>
<% if @book.errors.any? %>
  <div class="alert">
    <div class="alert_message">
      <%= @book.errors.count %> errors prohibited this book from being saved:
    </div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <%= form_with model:@book, url:"/books", local:true do |f| %>
    <div>Title</div>
    <%= f.text_field :title %>
    <div class="index_form">Body</div>
    <%= f.text_area :body %>
    <div class="index_form"><%= f.submit 'Create Book' %></div>
  <% end %>
<% else %>
  <%= form_with model:@book, url:"/books", local:true do |f| %>
    <div>Title</div>
    <%= f.text_field :title, value: @book.title %>
    <div class="index_form">Body</div>
    <%= f.text_area :body, value: @book.body %>
    <div class="index_form"><%= f.submit 'Create Book' %></div>
  <% end %>
<% end %>

app/views/books/show.html.erb
 <% flash.each do |message_type, message| %>
      <p class ="message_color"><%= message %></p>
 <% end %>
<p><strong>Title:</strong> <%= @book.title %></p>
<p><strong>Body:</strong> <%= @book.body %></p>

<%= link_to "Edit", edit_book_path(params[:id]), class: "show_btn" %> | <%= link_to "Back","/books", class: "show_btn" %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

<p><%= link_to "start","/books" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>